# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c772c05dd65ebee65367aea641dfecb373398ec147998435c0ade34dc900c1e7406c4c8e55a83cf9304fe23f764dfd95698d65fb4e183348b76200ac01d2696c

test:
  secret_key_base: 569e47c212bc35c973fd77c926fa44e8b62c133f58268f1a27786bd4848b3477714f96787ac077503418e24954f99e6bcce9bf70e083de5ddaab57cf88f6063d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
